
#公共配置
spring:
  profiles:
    active: test
  datasource:
    url: jdbc:postgresql://45.32.64.33:5432/postgres?useSSL=false&allowMultiQueries=true #主机地址:端口（一般是5432）/数据库名字
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver
  autoconfigure:
  servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 300MB


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.fastdfs.dao


fdfs:
  so-timeout: 1500
  connect-timeout: 600
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list: 45.32.64.33:22122  #tracker路径，TrackerList参数,支持多个
